public class SimulationEngine {
    // Change: Now accepts the Interface 'ReplacementAlgorithm' instead of 'int choice'
    public static void simulate(String refString, int frameSize, ReplacementAlgorithm algo, String algoName) {
        MemoryFrame memory = new MemoryFrame(frameSize);
        int pageFaults = 0;
        String[] pages = refString.split("");

        for (int i = 0; i < pages.length; i++) {
            String currentPage = pages[i];
            System.out.println("\nReference string: " + currentPage);

            if (memory.contains(currentPage)) {
                memory.display();
            } else {
                if (!memory.isFull()) {
                    memory.updateFrame(memory.getFirstEmptyIndex(), currentPage);
                    memory.display();
                } else {
                    System.out.println("=> Page Fault!");
                    pageFaults++;

                    // PURE DELEGATION:
                    int victimIndex = algo.findVictim(memory, pages, i);

                    String victimPage = memory.getPageAt(victimIndex);
                    System.out.println("Replace " + victimPage + " with " + currentPage);
                    memory.updateFrame(victimIndex, currentPage);
                    memory.display();
                }
            }
        }
        System.out.println("\nTotal " + pageFaults + " Page Fault(s) generated by " + algoName + "!");
    }
}